# Generated by Django 5.2.16 on 2026-07-27 23:16

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('reception', 'Réception fournisseur'), ('vente', 'Vente'), ('casse', 'Casse'), ('perte', 'Perte'), ('offert', 'Offert'), ('inventaire', "Correction d'inventaire")], max_length=12)),
                ('quantite', models.IntegerField(help_text='Positif pour une entrée, négatif pour une sortie.')),
                ('prix_unitaire', models.PositiveIntegerField(blank=True, help_text="Prix d'achat à la réception, en FCFA.", null=True)),
                ('commentaire', models.CharField(blank=True, max_length=160)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, help_text='Renseigné pour les sorties déclenchées par une vente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='ventes.commande')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='stock.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['produit', 'cree_le'], name='stock_mouve_produit_e23864_idx')],
            },
        ),
    ]
