# Generated by Django 5.2.16 on 2026-08-10 18:18

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInventaire',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(help_text='Ex : Inventaire semaine du 10/08/2026', max_length=160)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "session d'inventaire",
                'verbose_name_plural': "sessions d'inventaire",
                'ordering': ['-date', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.IntegerField()),
                ('stock_physique', models.IntegerField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='catalogue.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.sessioninventaire')),
            ],
            options={
                'ordering': ['produit__categorie__ordre', 'produit__nom'],
                'unique_together': {('session', 'produit')},
            },
        ),
    ]
