# Generated by Django 5.2.16 on 2026-07-27 23:16

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableResto',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('couverts_defaut', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_recu', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('type', models.CharField(choices=[('place', 'Sur place'), ('emporter', 'À emporter'), ('livraison', 'Livraison')], default='place', max_length=12)),
                ('origine', models.CharField(choices=[('comptoir', 'Comptoir'), ('whatsapp', 'WhatsApp (saisie manuelle)')], default='comptoir', max_length=12)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cuisine', 'En préparation'), ('prete', 'Prête'), ('en_route', 'En route'), ('livree', 'Livrée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='ouverte', max_length=12)),
                ('couverts', models.PositiveSmallIntegerField(default=1)),
                ('client_nom', models.CharField(blank=True, max_length=80)),
                ('client_telephone', models.CharField(blank=True, max_length=25)),
                ('client_adresse', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True, help_text='Ex. « peu pimenté ». Reporté sur le bon de cuisine.')),
                ('addition_demandee', models.BooleanField(default=False, help_text="Le client a demandé l'addition. Indépendant de l'avancement en cuisine.")),
                ('ouverte_le', models.DateTimeField(auto_now_add=True)),
                ('cloturee_le', models.DateTimeField(blank=True, null=True)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='livraison.livreur')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='ventes.tableresto')),
            ],
            options={
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'ordering': ['cree_le', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('tmoney', 'TMoney'), ('flooz', 'Flooz'), ('carte', 'Carte bancaire')], default='especes', max_length=10)),
                ('montant', models.PositiveIntegerField(help_text='Montant imputé à la commande, en FCFA.')),
                ('montant_recu', models.PositiveIntegerField(blank=True, help_text='Espèces remises par le client, pour calculer la monnaie.', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.commande')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'ouverte_le'], name='ventes_comm_statut_57bedb_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['cloturee_le'], name='ventes_comm_cloture_bf7b6c_idx'),
        ),
    ]
