# Generated by Django 5.2.16 on 2026-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero_jour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
