# Generated by Django 5.2.16 on 2026-07-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='addition_demandee',
            field=models.BooleanField(default=False, help_text="Le client a demandé l'addition. Indépendant de l'avancement en cuisine."),
        ),
    ]
