# Generated by Django 5.2.16 on 2026-07-27 23:16

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouverte_le', models.DateTimeField(auto_now_add=True)),
                ('fond_initial', models.PositiveIntegerField(default=0)),
                ('fermee_le', models.DateTimeField(blank=True, null=True)),
                ('montant_reel', models.PositiveIntegerField(blank=True, help_text='Espèces réellement comptées à la fermeture.', null=True)),
                ('commentaire_cloture', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'session de caisse',
                'verbose_name_plural': 'sessions de caisse',
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('achats_bar', 'Achats bar'), ('achats_cuisine', 'Achats cuisine'), ('transport', 'Transport'), ('salaires', 'Salaires'), ('energie', 'Électricité / Eau'), ('entretien', 'Entretien'), ('autres', 'Autres')], default='autres', max_length=20)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('montant', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('tmoney', 'TMoney'), ('flooz', 'Flooz'), ('banque', 'Banque / Carte')], default='especes', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['cree_le'], name='caisse_depe_cree_le_ba2212_idx')],
            },
        ),
    ]
