# Generated by Django 5.2.16 on 2026-08-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='supprime_le',
            field=models.DateTimeField(blank=True, help_text="Renseigné lors d'une suppression (soft-delete). La dépense reste traçable dans l'historique.", null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='supprime_par',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['supprime_le'], name='caisse_depe_supprim_7d7264_idx'),
        ),
    ]
