# Generated by Django 5.2.16 on 2026-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_depense_soft_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='commentaire_cloture',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='fermee_le',
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='cloturee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='remarques',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='montant_reel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['ouverte_le'], name='caisse_sess_ouverte_c02898_idx'),
        ),
    ]
