# Generated by Django 5.2.16 on 2026-07-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('rayon', models.CharField(choices=[('bar', 'Bar'), ('cuisine', 'Cuisine')], default='bar', max_length=10)),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône Tabler, sans le préfixe « ti- ».", max_length=40)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('prix_standard', models.PositiveIntegerField(blank=True, help_text='En FCFA. Vide pour les plats, dont le prix est saisi à la vente.', null=True)),
                ('prix_libre', models.BooleanField(default=False, help_text='Le prix est demandé au caissier à chaque ligne de commande.')),
                ('gere_stock', models.BooleanField(default=True, help_text='Faux pour la cuisine, préparée à la commande.')),
                ('seuil_alerte', models.PositiveSmallIntegerField(default=12, help_text='En dessous de ce stock, le produit est signalé « Bas ».')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.categorie')),
            ],
            options={
                'ordering': ['categorie__ordre', 'nom'],
            },
        ),
    ]
