# Generated by Django 5.2.16 on 2026-07-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône Tabler, sans le préfixe « ti- ».", max_length=40)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'famille',
                'verbose_name_plural': 'familles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='famille',
            field=models.ForeignKey(blank=True, help_text="Regroupement d'affichage. Supprimer une famille délie ses catégories, sans les perdre.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalogue.famille'),
        ),
    ]
